name: 'Rev store action'
description: 'Provide storing mechanism for beta releases'
author: 'APS'

# # Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  repo_token:
    description: 'Token for variable access'
    required: true

  var_name:
    description: 'Variable name for storing'
    required: true
    default: 'REV'

  tag_name:
    description: 'Tag name for storing'
    required: true

  size:
    description: 'Maximum store array items'
    required: true
    default: 350

  remove_request:
    description: 'Need to remove detected revision'
    required: true
    default: false

# Define your outputs here.
outputs:
  rev_is_changed:
    description: 'Status of changing version'

runs:
  using: node20
  main: dist/index.js
